name: Build Vue

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: 'suchomelova-dana'
          reponame: 'SK-TRASKO-Vyskov'
          token: ${{ secrets.GITHUB_TOKEN }}
